### ISSUE TITLE
rotating responses

### ISSUE THREAD

**Issue by tponthieux** [gabrielfalcao/HTTPretty#23]
In the section "rotating responses" you may want to mention that you can register more than two responses. Something like "you can register as many responses as needed." The wording of the documentation led me to believe that two is the limit.

**Comment by ensonic** [comment]
Sorry to comment on a old issue, it seems that despite can register e.g. 10 responses, only the first and the last will be used. Hence it it a bit pointless to lets say register 4 of them.
Can someone confirm that the replies with be [0, 3, 3, 3, 3, 3] instead of [0, 1, 2, 3, 3, 3]? At least this is what I see.
